// <auto-generated />
using System;
using Global.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Global.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Global.Domain.Entities.MedidorEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("MoradorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_morador");

                    b.Property<DateTime>("data_medida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("valor_consumo")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("valor_corrente")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("valor_tensao")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("id");

                    b.HasIndex("MoradorId");

                    b.ToTable("GS_MEDIDOR");
                });

            modelBuilder.Entity("Global.Domain.Entities.MoradorEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id");

                    b.ToTable("GS_MORADOR");
                });

            modelBuilder.Entity("Global.Domain.Entities.MedidorEntity", b =>
                {
                    b.HasOne("Global.Domain.Entities.MoradorEntity", "Morador")
                        .WithMany("Medidor")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("Global.Domain.Entities.MoradorEntity", b =>
                {
                    b.Navigation("Medidor");
                });
#pragma warning restore 612, 618
        }
    }
}
